// SPDX-License-Identifier: GPL-2.0-only

// Code generated by bpf2go; DO NOT EDIT.
//go:build mips

package cmd

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadGateway returns the embedded CollectionSpec for gateway.
func loadGateway() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GatewayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gateway: %w", err)
	}

	return spec, err
}

// loadGatewayObjects loads gateway and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gatewayObjects
//	*gatewayPrograms
//	*gatewayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGatewayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGateway()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gatewaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gatewaySpecs struct {
	gatewayProgramSpecs
	gatewayMapSpecs
	gatewayVariableSpecs
}

// gatewayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gatewayProgramSpecs struct {
	TcWanEgress  *ebpf.ProgramSpec `ebpf:"tc_wan_egress"`
	TcWanIngress *ebpf.ProgramSpec `ebpf:"tc_wan_ingress"`
}

// gatewayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gatewayMapSpecs struct {
	GwConfig *ebpf.MapSpec `ebpf:"gw_config"`
	GwEvents *ebpf.MapSpec `ebpf:"gw_events"`
}

// gatewayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gatewayVariableSpecs struct {
}

// gatewayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type gatewayObjects struct {
	gatewayPrograms
	gatewayMaps
	gatewayVariables
}

func (o *gatewayObjects) Close() error {
	return _GatewayClose(
		&o.gatewayPrograms,
		&o.gatewayMaps,
	)
}

// gatewayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type gatewayMaps struct {
	GwConfig *ebpf.Map `ebpf:"gw_config"`
	GwEvents *ebpf.Map `ebpf:"gw_events"`
}

func (m *gatewayMaps) Close() error {
	return _GatewayClose(
		m.GwConfig,
		m.GwEvents,
	)
}

// gatewayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type gatewayVariables struct {
}

// gatewayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type gatewayPrograms struct {
	TcWanEgress  *ebpf.Program `ebpf:"tc_wan_egress"`
	TcWanIngress *ebpf.Program `ebpf:"tc_wan_ingress"`
}

func (p *gatewayPrograms) Close() error {
	return _GatewayClose(
		p.TcWanEgress,
		p.TcWanIngress,
	)
}

func _GatewayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gateway_mips_bpfeb.o
var _GatewayBytes []byte
